export const notifications = [
  {
    title: "abc1",
    content:
      "cdefaskjdasjdahslkdasdkashlkdh;lsnhjkdkjasbdjasvdjkasvdaksvdkjadvakdvaiudbasvdausdkasskasnlanvlasblgibvibwibblasiblaisbdlasbiabljbaldbalsblacblavldvbaivblvbvlabvlablasilavclasvalsivalciavblab",
  },
  {
    title: "abc2",
    content: "cdef",
  },
  {
    title: "abc3",
    content: "cdef",
  },
  {
    title: "abc4",
    content: "cdef",
  },
  {
    title: "abc5",
    content: "cdef",
  },
  {
    title: "abc6",
    content: "cdef",
  },
];

export const classesNotifications = [
  {
    title: "class_abc1",
    content: "cdef",
  },
  {
    title: "class_abc2",
    content: "cdef",
  },
  {
    title: "class_abc3",
    content: "cdef",
  },
  {
    title: "class_abc4",
    content: "cdef",
  },
  {
    title: "class_abc5",
    content: "cdef",
  },
  {
    title: "class_abc6",
    content: "cdef",
  },
];

export const userInfo = {
  phone: "0935013191",
  birthday: "5/6/1999",
  student_name: "TRƯƠNG ĐĂNG ĐÔNG",
  sutdent_id: "102170077",
  class_name: "17T2",
  personal_email: "dangdong.truong5619@gmail.com",
  school_mail: "102170077@sv.dut.edu.vn",
  medical_id: "SV4484821180089",
  medical_id_end: "31/12/2021",
  personal_image: "http://cb.dut.udn.vn/ImageSV/17/102170077.jpg",
};

export const results = [
  {
    semester: "1/2017-2018",
    registered_credit: 16.0,
    relearn_credit: null,
    avg_b4: 2.94,
    avg_scholar: 7.48,
    avg_b10: 7.48,
    study_classify: "Bình thường",
    moral_points: 82.0,
    warnings: "",
    saved_credits: 16.0,
    avg_saved_credit_b4: 2.94,
    avg_moral: 82.0,
  },
  {
    semester: "2/2017-2018",
    registered_credit: 19.0,
    relearn_credit: null,
    avg_b4: 2.03,
    avg_scholar: 6.05,
    avg_b10: 6.05,
    study_classify: "Bình thường",
    moral_points: 84.0,
    warnings: "",
    saved_credits: 35.0,
    avg_saved_credit_b4: 2.44,
    avg_moral: 83.0,
  },
  {
    semester: "1/2018-2019",
    registered_credit: 18.5,
    relearn_credit: null,
    avg_b4: 2.32,
    avg_scholar: 6.43,
    avg_b10: 6.43,
    study_classify: "Bình thường",
    moral_points: 84.0,
    warnings: "",
    saved_credits: 53.5,
    avg_saved_credit_b4: 2.4,
    avg_moral: 83.0,
  },
  {
    semester: "2/2018-2019",
    registered_credit: 20.5,
    relearn_credit: null,
    avg_b4: 1.61,
    avg_scholar: 5.45,
    avg_b10: 5.45,
    study_classify: "Yếu",
    moral_points: 84.0,
    warnings: "",
    saved_credits: 71.0,
    avg_saved_credit_b4: 2.27,
    avg_moral: 84.0,
  },
  {
    semester: "1/2019-2020",
    registered_credit: 23.5,
    relearn_credit: 3.0,
    avg_b4: 1.89,
    avg_scholar: 6.37,
    avg_b10: 5.89,
    study_classify: "Yếu",
    moral_points: 85.0,
    warnings: "",
    saved_credits: 89.5,
    avg_saved_credit_b4: 2.3,
    avg_moral: 84.0,
  },
  {
    semester: "2/2019-2020",
    registered_credit: 14.5,
    relearn_credit: null,
    avg_b4: 2.59,
    avg_scholar: 6.64,
    avg_b10: 6.64,
    study_classify: "Bình thường",
    moral_points: 89.0,
    warnings: "",
    saved_credits: 102.0,
    avg_saved_credit_b4: 2.39,
    avg_moral: 85.0,
  },
  {
    semester: "1/2020-2021",
    registered_credit: 16.5,
    relearn_credit: null,
    avg_b4: 2.27,
    avg_scholar: 5.96,
    avg_b10: 5.96,
    study_classify: "Bình thường",
    moral_points: 84.0,
    warnings: "",
    saved_credits: 116.5,
    avg_saved_credit_b4: 2.41,
    avg_moral: 73.0,
  },
  {
    semester: "2/2020-2021",
    registered_credit: 24.5,
    relearn_credit: 7.0,
    avg_b4: null,
    avg_scholar: null,
    avg_b10: null,
    study_classify: "",
    moral_points: null,
    warnings: "",
    saved_credits: null,
    avg_saved_credit_b4: null,
    avg_moral: 64.0,
  },
];

export const course = [
  {
    semester: "2/2020-2021",
    credit: 2.0,
    cc: "",
    ck: "",
    da: "",
    gk: "",
    lt: "",
    th: "",
    t10: "",
    t4: "",
    bt: "",
    bv: "",
    index: 72,
    course_code: "1021793.2020.17.11B",
    course_name: "Đồ án chuyên ngành CNPM",
    point_formular: "[DA]*0.30+[CK]*0.70",
    BT: "",
    BV: "",
    CC: "",
    CK: "",
    DA: "",
    GK: "",
    LT: "",
    TH: "",
    T10: "",
    T4: "",
    as_text: "",
  },
  {
    semester: "2/2020-2021",
    credit: 2.0,
    cc: "",
    ck: "",
    da: "",
    gk: "",
    lt: "",
    th: "",
    t10: "",
    t4: "",
    bt: "",
    bv: "",
    index: 71,
    course_code: "1020413.2020.17.11A",
    course_name: "Kiểm thử phần mềm",
    point_formular: "[GK]*0.20+[BT]*0.20+[CK]*0.60",
    BT: "",
    BV: "",
    CC: "",
    CK: "",
    DA: "",
    GK: "",
    LT: "",
    TH: "",
    T10: "",
    T4: "",
    as_text: "",
  },
];

export const tests = [
  {
    index: 1,
    course_code: "1021883.2020.17.11A",
    course_name: "CĐ CN phần mềm",
    test_group: "A",
    test_grouping: "false",
    test_schedule: "",
  },
  {
    index: 2,
    course_code: "1080491.2020.19.86",
    course_name: "Cơ học ứng dụng",
    test_group: "A",
    test_grouping: "false",
    test_schedule: "",
  },
  {
    index: 3,
    course_code: "1021793.2020.17.11B",
    course_name: "ĐA Chuyên ngành CNPM",
    test_group: "-",
    test_grouping: "false",
    test_schedule: "Ngày: 22/05/2021, Phòng: H301, Giờ: 8h15, Xuất: 3C2",
  },
  {
    index: 4,
    course_code: "2090121.2020.18.23",
    course_name: "Đường lối CM của ĐCS Việt Nam",
    test_group: "-",
    test_grouping: "false",
    test_schedule: "Ngày: 23/05/2021, Phòng: F101, Giờ: 7h00, Xuất: 2C1",
  },
];
